### PR TITLE
Better docs for archiving requiring routed sessions

### PR DESCRIPTION
**Pull request by jeffswartz**

### CODE REVIEW

**Comment by aoberoi** [comment]
please see my related comment from the PHP SDK: https://github.com/opentok/OpenTok-PHP-SDK/pull/144#discussion_r61534901

**Comment by aoberoi** [comment]
@jeffswartz i've got similar concerns to those in https://github.com/opentok/Opentok-Java-SDK/pull/98#issuecomment-217040087

**Comment by aoberoi** [comment]
@jeffswartz care to comment on my response above? lets try to close this one up.

**Comment by maikthomas** [comment]
@jeffswartz should we close this?

**Comment by msach22** [comment]
@jeffswartz @maikthomas closing out this one in favor of this one https://github.com/opentok/opentok-node/pull/181

**Pull request closed without merging**
