### PR TITLE
Throw server errors for 503

### PR DESCRIPTION
**Pull request by ametaireau**
On 503, the library isn't throwing the right error otherwise.

### CODE REVIEW

**Comment by ametaireau** [comment]
@aoberoi do you have some feedback?

**Comment by aoberoi** [comment]
thanks for the PR! good catch and the fix looks good to me. one small nit: could your added test case is actually an improvement on the one right above it, would you mind updating the PR by just removing that existing test case?

**Comment by ametaireau** [comment]
Sure, I've now updated the PR to reflec that change.

**Comment by aoberoi** [comment]
thanks!

**Pull request merged**
