### PR TITLE
feat: adding support for captions

### PR DESCRIPTION
**Pull request by manchuck**
#### What is this PR doing?
This is adding support to start and stop captions

#### How should this be manually tested?
Start and stop captions for a stream

### CODE REVIEW

**Review by dragonmantank — APPROVED** [review]

**Comment by manchuck** [comment]
We do not have any type definitions for OpenTok, and since we are deprecating It, we will not add them in.

**Comment by sravidavi** [comment]
> We do not have any type definitions for OpenTok, and since we are deprecating It, we will not add them in.

Got it. Deprecating for using what?

**Comment by sravidavi** [comment]
> We do not have any type definitions for OpenTok, and since we are deprecating It, we will not add them in.

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/opentok

I mean this

**Comment by sravidavi** [comment]
cc @andreataglia - this package will be deprecated

**Pull request merged**
